const state={page:'overview',range:'7d',bootstrap:null,cache:new Map(),token:sessionStorage.getItem('finops_token')||'',lastExport:[]};
const pageMeta={overview:['经营总览','现金、消耗、成本与毛利'],users:['用户账务与利润','逐个用户核对充值、消耗与贡献'],accounts:['账号台账与成本','采购、摊销、闲置与回本'],usage:['用量与扣费','模型、Token 与单位经济性'],suppliers:['供应商与采购','上游资源、采购批次与已入账毛利'],funds:['充值与资金','现金流入、退款与采购支出'],reconciliation:['对账中心','来源数据、台账和成本守恒'],costs:['成本核算','成本模板、生效期和分摊方式'],sync:['数据同步','来源进度、延迟与错误状态'],alerts:['告警中心','缺失成本、到期、同步与对账差异']};
const content=document.querySelector('#content'),title=document.querySelector('#page-title'),subtitle=document.querySelector('#page-subtitle');
const rangeSelect=document.querySelector('#range-select'),rangeTabs=document.querySelector('#range-tabs'),refreshButton=document.querySelector('#refresh-button'),sidebarRefresh=document.querySelector('#sidebar-refresh'),syncStatus=document.querySelector('#sync-status');
const escapeHtml=(value)=>String(value??'').replace(/[&<>'"]/g,(char)=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
const money=(value,currency=state.bootstrap?.baseCurrency||'CNY')=>new Intl.NumberFormat('zh-CN',{style:'currency',currency,maximumFractionDigits:2}).format(Number(value||0));
const cny=(value)=>money(value,'CNY');
const usdValue=(value)=>money(value,'USD');
const compact=(value)=>new Intl.NumberFormat('zh-CN',{notation:'compact',maximumFractionDigits:2}).format(Number(value||0));
const percent=(value)=>value===null||value===undefined?'--':`${(Number(value)*100).toFixed(1)}%`;
const dateTime=(value)=>value?new Intl.DateTimeFormat('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}).format(new Date(value)):'--';
const icon=(name)=>`<img src="/icons/${name}.svg" alt="">`;
function api(path,options={}){const url=new URL(`/api${path}`,location.origin);if(options.range!==false)url.searchParams.set('range',state.range);return fetch(url,{...options,headers:{'Content-Type':'application/json',...(state.token?{Authorization:`Bearer ${state.token}`}:{ }),...(options.headers||{})}}).then(async(response)=>{if(response.status===401){const token=prompt('请输入 FinOps 管理令牌');if(token){state.token=token;sessionStorage.setItem('finops_token',token);return api(path,options);}throw new Error('未授权');}const data=await response.json();if(!response.ok)throw new Error(data.error||'请求失败');return data;});}
function metric(label,value,hint='',tone=''){return `<div class="metric ${tone}"><div class="label">${label}</div><div class="value">${value}</div><div class="hint">${hint}</div></div>`;}
function section(titleText,desc){return `<div class="section-heading"><div><h2>${titleText}</h2><p>${desc}</p></div></div>`;}
function tags(values=[]){return values.map((value)=>`<span class="tag">${escapeHtml(value)}</span>`).join('')||'<span class="secondary-text">未标记</span>';}
function profitClass(value){return Number(value)>=0?'money-positive':'money-negative';}
function costCoverage(item){return item.costCoverageStatus==='complete'?'<span class="status">已核算</span>':`<span class="status warning">待补成本${item.unbookedAccountCount?` · ${compact(item.unbookedAccountCount)} 账号`:''}</span>`;}
function toast(message){const el=document.querySelector('#toast');el.textContent=message;el.hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.hidden=true,2600);}
function setRange(range){if(!range||range===state.range&&rangeSelect?.value===range)return;state.range=range;if(rangeSelect)rangeSelect.value=range;rangeTabs?.querySelectorAll('[data-range]').forEach((button)=>{const active=button.dataset.range===range;button.classList.toggle('active',active);button.setAttribute('aria-pressed',String(active));});render();}
function setRefreshState(active){[refreshButton,sidebarRefresh].forEach((button)=>{if(!button)return;button.disabled=active;button.classList.toggle('is-spinning',active);});}
function applySyncState(sync){const status=sync?.status||'pending';syncStatus?.classList.toggle('pending',status==='pending');syncStatus?.classList.toggle('error',status!=='healthy'&&status!=='pending');if(document.querySelector('#sync-label'))document.querySelector('#sync-label').textContent=status==='healthy'?'同步正常':status==='pending'?'等待首次同步':'同步异常';if(document.querySelector('#sync-detail'))document.querySelector('#sync-detail').textContent=sync?.lagSeconds===null||sync?.lagSeconds===undefined?'尚无数据':`延迟 ${Math.round(sync.lagSeconds)} 秒`;}
function table(headers,rows,minWidth=900){return `<div class="table-scroll"><table class="data-table" style="min-width:${minWidth}px"><thead><tr>${headers.map((h)=>`<th class="${h.right?'number':''}">${h.label}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.map((row)=>`<tr>${row.map((cell,index)=>`<td class="${headers[index]?.right?'number':''}">${cell}</td>`).join('')}</tr>`).join(''):`<tr><td colspan="${headers.length}" class="empty">当前范围没有数据</td></tr>`}</tbody></table></div>`;}
function drawTrend(canvas,items){const rect=canvas.getBoundingClientRect(),dpr=devicePixelRatio||1;canvas.width=rect.width*dpr;canvas.height=rect.height*dpr;const ctx=canvas.getContext('2d');ctx.scale(dpr,dpr);const w=rect.width,h=rect.height,p={l:44,r:14,t:18,b:34};ctx.clearRect(0,0,w,h);if(!items.length)return;const keys=[['revenue','#2f6feb'],['bookedCostCny','#d85d18'],['bookedProfitCny','#178545']],max=Math.max(...items.flatMap((item)=>keys.map(([key])=>Number(item[key]||0))))*1.12||1;ctx.font='10px Microsoft YaHei';ctx.fillStyle='#76818a';ctx.strokeStyle='#e8ecee';ctx.lineWidth=1;for(let i=0;i<5;i++){const y=p.t+(h-p.t-p.b)*i/4;ctx.beginPath();ctx.moveTo(p.l,y);ctx.lineTo(w-p.r,y);ctx.stroke();ctx.fillText(compact(max*(1-i/4)),4,y+3);}keys.forEach(([key,color])=>{ctx.strokeStyle=color;ctx.lineWidth=2;ctx.beginPath();items.forEach((item,index)=>{const x=p.l+(w-p.l-p.r)*(index/(Math.max(1,items.length-1))),y=p.t+(h-p.t-p.b)*(1-Number(item[key]||0)/max);index?ctx.lineTo(x,y):ctx.moveTo(x,y);});ctx.stroke();});items.forEach((item,index)=>{if(index%Math.ceil(items.length/7)!==0&&index!==items.length-1)return;const x=p.l+(w-p.l-p.r)*(index/(Math.max(1,items.length-1)));ctx.fillStyle='#76818a';ctx.fillText(item.day.slice(5),x-12,h-10);});[['确认收入','#2f6feb'],['已入账成本','#d85d18'],['已入账毛利','#178545']].forEach(([label,color],index)=>{ctx.fillStyle=color;ctx.fillRect(p.l+index*88,2,9,3);ctx.fillStyle='#58636c';ctx.fillText(label,p.l+14+index*88,7);});}
async function renderOverview(){
  const [summaryData,trend,models]=await Promise.all([api('/summary'),api('/trend'),api('/usage/models')]);
  state.lastExport=models;
  const op=summaryData.operations, cashData=summaryData.cash;
  content.innerHTML=`${section('现金','人民币现金收付与采购支出')}
    <div class="metric-grid">${metric('充值现金',cny(cashData.received),'balance 订单实付')}${metric('订阅现金',cny(cashData.subscriptionReceived),'subscription 订单实付')}${metric('现金退款',cny(cashData.refunds),'按支付比例折算','warn')}${metric('采购支出',cny(cashData.procurementSpend),'账号与供应商成本','warn')}${metric('现金净流入',cny(cashData.netInflow),'现金流口径',cashData.netInflow>=0?'good':'bad')}</div>
    ${section('经营核算','人民币确认收入与已登记 CNY 成本核算')}
    <div class="metric-grid">${metric('已确认收入',cny(op.recognizedRevenueCny??op.revenue),'按充值/赠送批次 FIFO 确认')}${metric('用户余额扣费',cny(op.userChargeCny),'用户实际消耗，不等于确认收入')}${metric('采购分摊成本',cny(op.purchaseAllocatedCostCny??op.allocatedCost),'站长登记的人民币成本')}${metric('已入账成本',cny(op.bookedCostCny??op.effectiveCostCny),'仅包含已有 CNY 成本期间','warn')}${metric('成本覆盖',op.unbookedAccountCount?`待补 ${compact(op.unbookedAccountCount)} 个账号`:'已覆盖',op.unbookedAccountCount?`影响确认收入 ${cny(op.unbookedRevenueCny)}`:'当前有用量账号均已登记',op.unbookedAccountCount?'warn':'good')}${metric('已入账毛利',cny(op.bookedProfitCny??op.grossProfitCny),'不含待补成本',op.grossProfit>=0?'good':'bad')}${metric('已入账毛利率',percent(op.grossMargin),'成本未覆盖时仅供暂估',op.unbookedAccountCount?'warn':op.grossMargin>=.2?'good':'warn')}</div>
    ${section('用量','请求与 Token 规模')}<div class="metric-grid">${metric('请求',compact(summaryData.usage.requests),'当前周期')}${metric('输入 Token',compact(summaryData.usage.inputTokens),'Input')}${metric('输出 Token',compact(summaryData.usage.outputTokens),'Output')}${metric('缓存 Token',compact(summaryData.usage.cacheTokens),'创建与读取')}${metric('平均耗时',`${(summaryData.usage.averageLatencyMs/1000).toFixed(2)}s`,`${summaryData.usage.activeUsers} 用户 · ${summaryData.usage.activeAccounts} 账号`)}</div>
    <div class="split"><section class="panel"><div class="panel-header"><h2>人民币收入与成本趋势</h2><span>按日</span></div><div class="chart-wrap"><canvas id="trend-chart"></canvas></div></section><section class="panel"><div class="panel-header"><h2>待处理事项</h2><span>${summaryData.alerts.length} 项</span></div><div class="alert-list">${summaryData.alerts.length?summaryData.alerts.map((a)=>`<div class="alert ${a.severity}"><span class="alert-dot"></span><div><strong>${escapeHtml(a.title)}</strong><p>${escapeHtml(a.detail)}</p></div></div>`).join(''):'<div class="empty">没有待处理事项</div>'}</div></section></div>
    <section class="table-panel"><div class="panel-header"><h2>模型单位经济性</h2><span>人民币扣费、确认收入与已入账成本</span></div>${table([{label:'模型'},{label:'请求',right:true},{label:'Token',right:true},{label:'标准牌价 USD',right:true},{label:'余额扣费 CNY',right:true},{label:'确认收入 CNY',right:true},{label:'已入账成本 CNY',right:true},{label:'已入账毛利 CNY',right:true},{label:'成本覆盖'}],models.map((m)=>[`<span class="primary-text">${escapeHtml(m.name)}</span>`,compact(m.requests),compact(m.tokens),usdValue(m.tokenListValueUsd),cny(m.userChargeCny),cny(m.recognizedRevenueCny??m.revenue),cny(m.bookedCostCny??m.effectiveCostCny),`<span class="${profitClass(m.bookedProfitCny??m.grossProfitCny)}">${cny(m.bookedProfitCny??m.grossProfitCny)}</span>`,costCoverage(m)]),1320)}</section>`;
  requestAnimationFrame(()=>drawTrend(document.querySelector('#trend-chart'),trend));
}
function searchTools(placeholder,actionLabel='',action='',searchValue=''){return `<div class="table-tools"><div class="search">${icon('search')}<input id="table-search" placeholder="${escapeHtml(placeholder)}" value="${escapeHtml(searchValue)}"></div>${actionLabel?`<button class="button primary" id="table-action" data-action="${action}">${icon('plus')}${actionLabel}</button>`:''}</div>`;}
async function renderUsers(search=''){const data=await api(`/users?search=${encodeURIComponent(search)}`);state.lastExport=data.items;content.innerHTML=`${section('用户核算','人民币充值、余额、扣费、确认收入与已入账成本分别核对')}<section class="table-panel">${searchTools('搜索邮箱、用户名','','',search)}${table([{label:'用户'},{label:'标签'},{label:'现金充值 CNY',right:true},{label:'入账余额 CNY',right:true},{label:'当前余额 CNY',right:true},{label:'余额扣费 CNY',right:true},{label:'确认收入 CNY',right:true},{label:'请求',right:true},{label:'Token',right:true},{label:'已入账成本 CNY',right:true},{label:'已入账毛利 CNY',right:true},{label:'成本覆盖'}],data.items.map((u)=>[`<span class="primary-text">${escapeHtml(u.email)}</span><div class="secondary-text">ID ${u.id}</div>`,tags(u.tags),cny(u.cashPaidCny),cny(u.creditedCny),cny(u.balanceCny),cny(u.userChargeCny),cny(u.recognizedRevenueCny??u.revenue),compact(u.requests),compact(u.tokens),cny(u.bookedCostCny??u.effectiveCostCny),`<span class="${profitClass(u.bookedProfitCny??u.grossProfitCny)}">${cny(u.bookedProfitCny??u.grossProfitCny)}</span>`,costCoverage(u)]),1660)}<div class="pager"><span>共 ${data.total} 位用户</span><span>第 ${data.page} 页</span></div></section>`;bindSearch(renderUsers);}
async function renderAccounts(search=''){const [data,profiles]=await Promise.all([api(`/accounts?search=${encodeURIComponent(search)}`),api('/cost-profiles',{range:false})]);state.lastExport=data.items;content.innerHTML=`${section('账号成本中心','人民币成本、用户扣费、确认收入与美元 Token 牌价分别展示')}<section class="table-panel">${searchTools('搜索账号、平台、供应商','登记采购成本','account-cost',search)}${table([{label:'账号'},{label:'平台/供应商'},{label:'成本类型'},{label:'有效期'},{label:'请求',right:true},{label:'Token',right:true},{label:'标准牌价 USD',right:true},{label:'余额扣费 CNY',right:true},{label:'确认收入 CNY',right:true},{label:'已入账成本 CNY',right:true},{label:'已入账毛利 CNY',right:true},{label:'成本覆盖'}],data.items.map((a)=>[`<span class="primary-text">${escapeHtml(a.name)}</span><div class="secondary-text">#${a.id} · ${tags(a.tags)}</div>`,`<span class="primary-text">${escapeHtml(a.platform)}</span><div class="secondary-text">${escapeHtml(a.supplier||'未标记供应商')}</div>`,`<span class="tag neutral">${escapeHtml(a.costType)}</span>`,a.expiresAt?new Date(a.expiresAt).toLocaleDateString('zh-CN'):'长期',compact(a.requests),compact(a.tokens),usdValue(a.tokenListValueUsd),cny(a.userChargeCny),cny(a.recognizedRevenueCny??a.revenue),cny(a.bookedCostCny??a.effectiveCostCny),`<span class="${profitClass(a.bookedProfitCny??a.grossProfitCny)}">${cny(a.bookedProfitCny??a.grossProfitCny)}</span>`,costCoverage(a)]),1640)}<div class="pager"><span>共 ${data.total} 个账号</span><span>第 ${data.page} 页</span></div></section>`;bindSearch(renderAccounts);document.querySelector('#table-action')?.addEventListener('click',()=>openAccountCostModal(data.items,profiles));}
async function renderSuppliers(search=''){
  const [data,accountData,profiles]=await Promise.all([api(`/suppliers?search=${encodeURIComponent(search)}`),api('/accounts?page_size=100'),api('/cost-profiles',{range:false})]);
  const summary=data.summary||{};
  state.lastExport=data.items;
  content.innerHTML=`${section('供应商经营概览','按供应商归集账号、人民币采购、用量和已入账毛利')}
    <div class="metric-grid">
      ${metric('供应商',compact(summary.supplierCount),'当前筛选范围')}
      ${metric('关联账号',compact(summary.accountCount),'已归集账号')}
      ${metric('期间采购',money(summary.purchaseSpend),'含手续费与税费','warn')}
      ${metric('已入账毛利',cny(summary.grossProfit),'确认收入减已登记 CNY 成本',Number(summary.grossProfit)>=0?'good':'bad')}
      ${metric('待补成本账号',compact(summary.unbookedAccountCount),'当前有用量但无成本期间',Number(summary.unbookedAccountCount)>0?'warn':'good')}
      ${metric('未标记供应商',compact(summary.missingSupplierAccounts),'需要补充账号标签',Number(summary.missingSupplierAccounts)>0?'warn':'good')}
    </div>
    ${section('供应商核算','实际成本仅来自站长登记的人民币成本期间')}
    <section class="table-panel">${searchTools('搜索供应商、平台、账号或采购批次','登记采购成本','account-cost',search)}${table([
      {label:'供应商'},{label:'平台'},{label:'账号',right:true},{label:'即将到期',right:true},{label:'请求',right:true},{label:'Token',right:true},
      {label:'确认收入 CNY',right:true},{label:'采购分摊 CNY',right:true},{label:'已入账成本 CNY',right:true},{label:'已入账毛利 CNY',right:true},{label:'毛利率',right:true},{label:'成本覆盖'}
    ],data.items.map((item)=>[
      `<span class="primary-text">${escapeHtml(item.supplier)}</span><div class="secondary-text">${item.missingRuleCount?`${item.missingRuleCount} 个账号缺成本规则`:'成本规则完整'}</div>`,
      tags(item.platforms),compact(item.accountCount),compact(item.expiringAccounts),compact(item.requests),compact(item.tokens),cny(item.recognizedRevenueCny??item.revenue),cny(item.purchaseAllocatedCostCny??item.purchaseSpend),cny(item.bookedCostCny??item.effectiveCostCny),
      `<span class="${profitClass(item.bookedProfitCny??item.grossProfitCny)}">${cny(item.bookedProfitCny??item.grossProfitCny)}</span>`,percent(item.grossMargin),costCoverage(item)
    ]),1400)}</section>
    ${section('采购批次','账号采购成本、生效期和供应商归属')}
    <section class="table-panel">${table([
      {label:'账号'},{label:'供应商/批次'},{label:'成本模板'},{label:'成本金额 CNY',right:true},{label:'含税费 CNY',right:true},{label:'生效期'},{label:'状态'}
    ],data.purchases.map((item)=>[
      `<span class="primary-text">${escapeHtml(item.accountName)}</span><div class="secondary-text">#${escapeHtml(item.accountId)}</div>`,
      `<span class="primary-text">${escapeHtml(item.supplier)}</span><div class="secondary-text">${escapeHtml(item.purchaseBatch)}</div>`,
      `<span class="tag neutral">${escapeHtml(item.costProfile)}</span>`,cny(item.originalAmount),cny(item.totalCost),
      `${item.effectiveFrom?new Date(item.effectiveFrom).toLocaleDateString('zh-CN'):'--'} - ${item.effectiveTo?new Date(item.effectiveTo).toLocaleDateString('zh-CN'):'长期'}`,
      `<span class="status ${item.status==='active'?'':item.status==='pending'?'warning':'error'}">${escapeHtml(item.status)}</span>`
    ]),1040)}</section>`;
  bindSearch(renderSuppliers);
  document.querySelector('#table-action')?.addEventListener('click',()=>openAccountCostModal(accountData.items,profiles));
}
async function renderUsage(){const models=await api('/usage/models');state.lastExport=models;content.innerHTML=`${section('模型与 Token','美元 Token 牌价仅作参考，人民币扣费、收入与已入账成本独立核算')}<section class="table-panel">${table([{label:'模型'},{label:'请求',right:true},{label:'Token',right:true},{label:'标准牌价 USD',right:true},{label:'余额扣费 CNY',right:true},{label:'确认收入 CNY',right:true},{label:'已入账成本 CNY',right:true},{label:'已入账毛利 CNY',right:true},{label:'成本覆盖'}],models.map((m)=>[`<span class="primary-text">${escapeHtml(m.name)}</span>`,compact(m.requests),compact(m.tokens),usdValue(m.tokenListValueUsd),cny(m.userChargeCny),cny(m.recognizedRevenueCny??m.revenue),cny(m.bookedCostCny??m.effectiveCostCny),`<span class="${profitClass(m.bookedProfitCny??m.grossProfitCny)}">${cny(m.bookedProfitCny??m.grossProfitCny)}</span>`,costCoverage(m)]),1360)}</section>`;}
async function renderFunds(search=''){const data=await api(`/funds?search=${encodeURIComponent(search)}`),summary=data.summary||{inflow:0,outflow:0,refunds:0,net:0,transactions:data.total};state.lastExport=data.items;content.innerHTML=`${section('资金概览','人民币现金流入、支出、退款与净额')}<div class="metric-grid">${metric('现金流入',cny(summary.inflow),'充值与其他收入','good')}${metric('现金流出',cny(summary.outflow),'采购、费用与退款','warn')}${metric('其中退款',cny(summary.refunds),'已确认现金退款')}${metric('现金净额',cny(summary.net),'流入减流出',summary.net>=0?'good':'bad')}${metric('流水笔数',compact(summary.transactions),'当前周期')}</div>${section('现金流水','所有实际资金与余额均按人民币记录')}<section class="table-panel">${searchTools('搜索流水编号、对方或费用类型','登记其他支出','expense',search)}${table([{label:'时间'},{label:'流水/对方'},{label:'类型'},{label:'支付方式'},{label:'方向'},{label:'金额 CNY',right:true},{label:'入账/退回余额 CNY',right:true},{label:'状态'}],data.items.map((t)=>[dateTime(t.occurredAt),`<span class="primary-text">${escapeHtml(t.reference)}</span><div class="secondary-text">${escapeHtml(t.party||'')}</div>`,`<span class="tag neutral">${escapeHtml(t.type)}</span>`,escapeHtml(t.method),t.direction==='in'?'<span class="money-positive">流入</span>':'<span class="money-negative">流出</span>',cny(t.baseAmountCny),t.creditedAmountCny||t.creditedAmount?cny(t.creditedAmountCny??t.creditedAmount):'--',`<span class="status">${escapeHtml(t.status)}</span>`]),1040)}<div class="pager"><span>共 ${data.total} 笔流水</span><span>第 ${data.page} 页</span></div></section>`;bindSearch(renderFunds);document.querySelector('#table-action')?.addEventListener('click',openExpenseModal);}
async function renderReconciliation(){const items=await api('/reconciliation');state.lastExport=items;const format=(value)=>cny(value);content.innerHTML=`${section('最近对账','全部按人民币账本核对，差异为 0 才代表一致')}<div class="recon-grid">${items.map((item)=>`<article class="recon-item"><header><h3>${escapeHtml(item.label)}</h3><span class="status ${item.status==='matched'?'':item.status==='warning'?'warning':'error'}">${item.status==='matched'?'一致':'需处理'}</span></header><div class="delta ${profitClass(-Math.abs(item.difference))}">${format(item.difference)}</div><p>源系统 ${format(item.sourceTotal)} · FinOps ${format(item.finopsTotal)}</p><p>检查时间 ${dateTime(item.checkedAt)}</p></article>`).join('')}</div>`;}
async function renderCosts(search=''){const profiles=await api('/cost-profiles',{range:false}),needle=search.trim().toLowerCase(),filtered=needle?profiles.filter((p)=>`${p.name} ${p.costType} ${p.currency} ${p.allocationMethod}`.toLowerCase().includes(needle)):profiles;state.lastExport=filtered;content.innerHTML=`${section('成本规则','规则版本化，修改不覆盖历史')}<section class="table-panel">${searchTools('搜索模板、成本类型或币种','新建成本模板','cost-profile',search)}${table([{label:'模板名称'},{label:'成本类型'},{label:'币种'},{label:'分摊方法'},{label:'版本',right:true},{label:'绑定账号',right:true}],filtered.map((p)=>[`<span class="primary-text">${escapeHtml(p.name)}</span>`,`<span class="tag neutral">${escapeHtml(p.costType)}</span>`,escapeHtml(p.currency),escapeHtml(p.allocationMethod),`v${p.version}`,p.accountCount]),760)}</section>`;bindSearch(renderCosts);document.querySelector('#table-action')?.addEventListener('click',openCostProfileModal);}
async function renderSync(){
  const data=await api('/sync-details',{range:false});
  const statusText=data.status==='healthy'?'同步正常':data.status==='error'?'同步异常':'等待同步';
  state.lastExport=data.sources;
  content.innerHTML=`${section('数据同步','逐个来源检查最近成功时间、延迟和错误')}
    <div class="metric-grid">
      ${metric('整体状态',statusText,`${data.sources.length} 个数据来源`,data.status==='healthy'?'good':data.status==='error'?'bad':'warn')}
      ${metric('最大延迟',data.lagSeconds===null?'--':`${Math.round(data.lagSeconds)}s`,'按最慢来源计算',Number(data.lagSeconds)>300?'warn':'')}
      ${metric('最近完整成功',dateTime(data.lastSuccessAt),'所有来源的最老成功时间')}
      ${metric('累计同步行数',compact(data.rowsSynced),'游标累计')}
      ${metric('异常来源',compact(data.errorCount),'需处理的同步错误',data.errorCount?'bad':'good')}
    </div>
    <section class="table-panel">${table([
      {label:'数据来源'},{label:'状态'},{label:'最近成功'},{label:'当前游标'},{label:'延迟',right:true},{label:'累计行数',right:true},{label:'错误信息'}
    ],data.sources.map((item)=>[
      `<span class="primary-text">${escapeHtml(item.label)}</span><div class="secondary-text">${escapeHtml(item.sourceName)}</div>`,
      `<span class="status ${item.status==='healthy'?'':item.status==='pending'?'warning':'error'}">${item.status==='healthy'?'正常':item.status==='pending'?'等待':'异常'}</span>`,
      dateTime(item.lastSuccessAt),dateTime(item.cursorTime),item.lagSeconds===null?'--':`${Math.round(item.lagSeconds)}s`,compact(item.rowsSynced),
      item.lastError?`<span class="money-negative">${escapeHtml(item.lastError)}</span>`:'<span class="secondary-text">无</span>'
    ]),980)}</section>`;
  applySyncState(data);
}
async function renderAlerts(){
  const [summaryData,syncData,reconciliation,supplierData]=await Promise.all([api('/summary'),api('/sync-details',{range:false}),api('/reconciliation'),api('/suppliers')]);
  const issues=(summaryData.alerts||[])
    .filter((item)=>!(item.severity==='low'&&/正常|健康/.test(`${item.title} ${item.detail}`)))
    .map((item,index)=>({id:`summary-${index}`,category:'经营核算',status:'open',...item}));
  reconciliation.filter((item)=>item.status!=='matched').forEach((item)=>issues.push({id:`recon-${item.type}`,category:'对账差异',severity:Math.abs(Number(item.difference))>100?'high':'medium',title:`${item.label}存在差异`,detail:`源系统与 FinOps 相差 ${cny(item.difference)}`,status:'open'}));
  syncData.sources.filter((item)=>item.status!=='healthy').forEach((item)=>issues.push({id:`sync-${item.sourceName}`,category:'数据同步',severity:item.status==='error'?'high':'medium',title:`${item.label}${item.status==='error'?'同步异常':'等待首次同步'}`,detail:item.lastError||'尚未形成可用同步游标',status:'open'}));
  const expiring=(supplierData.items||[]).reduce((sum,item)=>sum+Number(item.expiringAccounts||0),0);
  if(expiring)issues.push({id:'accounts-expiring',category:'账号治理',severity:'medium',title:`${expiring} 个账号将在 14 天内到期`,detail:'请核对续费计划、采购批次和剩余用量',status:'open'});
  const missingSupplier=Number(supplierData.summary?.missingSupplierAccounts||0);
  if(missingSupplier)issues.push({id:'supplier-missing',category:'供应商治理',severity:'medium',title:`${missingSupplier} 个账号未标记供应商`,detail:'采购成本无法稳定归集到上游',status:'open'});
  const high=issues.filter((item)=>item.severity==='high').length,medium=issues.filter((item)=>item.severity==='medium').length;
  state.lastExport=issues;
  content.innerHTML=`${section('待处理告警','成本、账号、同步和对账问题统一查看')}
    <div class="metric-grid">
      ${metric('待处理',compact(issues.length),'当前周期与实时状态',issues.length?'warn':'good')}
      ${metric('高优先级',compact(high),'建议优先处理',high?'bad':'good')}
      ${metric('中优先级',compact(medium),'需持续跟进',medium?'warn':'good')}
      ${metric('对账差异',compact(reconciliation.filter((item)=>item.status!=='matched').length),'未达到守恒')}
      ${metric('同步异常',compact(syncData.errorCount),'来源失败数',syncData.errorCount?'bad':'good')}
    </div>
    <section class="table-panel">${table([
      {label:'级别'},{label:'类型'},{label:'告警内容'},{label:'说明'},{label:'状态'}
    ],issues.map((item)=>[
      `<span class="severity-badge ${escapeHtml(item.severity)}">${item.severity==='high'?'高':item.severity==='medium'?'中':'低'}</span>`,
      escapeHtml(item.category),`<span class="primary-text">${escapeHtml(item.title)}</span>`,escapeHtml(item.detail),`<span class="status warning">待处理</span>`
    ]),880)}</section>`;
}
function bindSearch(handler){const input=document.querySelector('#table-search');let timer;input?.addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(()=>handler(input.value),260);});}
const renderers={overview:renderOverview,users:renderUsers,accounts:renderAccounts,usage:renderUsage,suppliers:renderSuppliers,funds:renderFunds,reconciliation:renderReconciliation,costs:renderCosts,sync:renderSync,alerts:renderAlerts};
async function render(){content.innerHTML='<div class="loading"><span></span>正在读取经营数据</div>';const [t,s]=pageMeta[state.page];title.textContent=t;subtitle.textContent=s;document.querySelectorAll('.nav-item').forEach((el)=>{const active=el.dataset.page===state.page;el.classList.toggle('active',active);if(active)el.setAttribute('aria-current','page');else el.removeAttribute('aria-current');});try{await renderers[state.page]();}catch(error){content.innerHTML=`<div class="empty"><strong>数据读取失败</strong><p>${escapeHtml(error.message)}</p><button class="button" id="retry">重新加载</button></div>`;document.querySelector('#retry')?.addEventListener('click',render);}}
function openModal(titleText,fields,onSubmit){document.querySelector('#modal-title').textContent=titleText;const form=document.querySelector('#modal-form');form.innerHTML=fields.map((f)=>`<label class="field ${f.full?'full':''}"><span>${escapeHtml(f.label)}</span>${f.type==='select'?`<select name="${escapeHtml(f.name)}" ${f.required===false?'':'required'}>${f.options.map(([v,l])=>`<option value="${escapeHtml(v)}">${escapeHtml(l)}</option>`).join('')}</select>`:f.type==='textarea'?`<textarea name="${escapeHtml(f.name)}" ${f.required===false?'':'required'}></textarea>`:`<input type="${f.type||'text'}" name="${escapeHtml(f.name)}" ${f.required===false?'':'required'} ${f.type==='number'?'step="any"':''} ${f.value!==undefined?`value="${escapeHtml(f.value)}"`:''}>`}</label>`).join('')+'<div class="form-actions"><button type="button" class="button" id="form-cancel">取消</button><button type="submit" class="button primary">保存</button></div>';document.querySelector('#modal-backdrop').hidden=false;document.querySelector('#form-cancel').onclick=closeModal;form.onsubmit=async(event)=>{event.preventDefault();const data=Object.fromEntries(new FormData(form));try{await onSubmit(data);closeModal();toast('已保存');await render();}catch(error){toast(error.message);}};}
function closeModal(){document.querySelector('#modal-backdrop').hidden=true;}
function openCostProfileModal(){openModal('新建成本模板',[{name:'name',label:'模板名称'},{name:'costType',label:'成本类型',type:'select',options:[['subscription','固定订阅'],['metered','按量后付费'],['prepaid','预付余额'],['one_time','一次性购买'],['free','免费资源'],['hybrid','混合成本']]},{name:'allocationMethod',label:'分摊方法',type:'select',options:[['standard_cost_weight','标准目录价权重'],['token_weight','Token 权重'],['none','不分摊']]},{name:'notes',label:'备注',type:'textarea',full:true,required:false}],(data)=>api('/cost-profiles',{method:'POST',range:false,body:JSON.stringify({...data,currency:'CNY'})}));}
function openExpenseModal(){const now=new Date(Date.now()-new Date().getTimezoneOffset()*60_000).toISOString().slice(0,16);openModal('登记其他支出',[{name:'transactionType',label:'费用类型',type:'select',options:[['other_expense','其他支出'],['gateway_fee','通道手续费'],['account_purchase','账号采购'],['supplier_topup','供应商充值'],['subscription_renewal','订阅续费'],['affiliate_rebate','分销返利'],['manual_adjustment','人工调整'],['refund','人工退款']]},{name:'originalAmount',label:'金额 CNY',type:'number'},{name:'paymentMethod',label:'支付方式',type:'select',options:[['bank','银行转账'],['alipay','支付宝'],['wechat','微信支付'],['card','银行卡'],['other','其他']]},{name:'occurredAt',label:'发生时间',type:'datetime-local',value:now},{name:'reference',label:'流水编号',required:false},{name:'party',label:'对方/供应商',required:false},{name:'notes',label:'备注',type:'textarea',full:true,required:false}],(data)=>api('/cash-transactions',{method:'POST',range:false,body:JSON.stringify({...data,direction:'out',originalCurrency:'CNY',fxRate:'1',baseAmount:data.originalAmount})}));}
function openAccountCostModal(accounts,profiles=[]){openModal('登记账号采购成本',[{name:'accountId',label:'账号',type:'select',options:accounts.map((a)=>[a.id,a.name])},{name:'costProfileId',label:'成本模板（可选）',type:'select',required:false,options:[['','不使用模板'],...profiles.map((p)=>[p.id,p.name])]},{name:'originalAmount',label:'成本金额 CNY',type:'number'},{name:'feeAmount',label:'手续费 CNY',type:'number',value:'0',required:false},{name:'taxAmount',label:'税费 CNY',type:'number',value:'0',required:false},{name:'effectiveFrom',label:'生效时间',type:'datetime-local'},{name:'effectiveTo',label:'结束时间',type:'datetime-local'},{name:'supplier',label:'供应商',required:false},{name:'purchaseBatch',label:'采购批次',required:false},{name:'tags',label:'账号标签（逗号分隔）',required:false},{name:'notes',label:'备注',type:'textarea',full:true,required:false}],(data)=>api('/account-cost-periods',{method:'POST',range:false,body:JSON.stringify({...data,originalCurrency:'CNY',fxRate:'1',baseAmount:data.originalAmount,tags:data.tags?data.tags.split(',').map((tag)=>tag.trim()).filter(Boolean):null})}));}
function exportCsv(){if(!state.lastExport.length)return toast('当前页面没有可导出数据');const keys=Object.keys(state.lastExport[0]),lines=[keys.join(','),...state.lastExport.map((row)=>keys.map((key)=>`"${String(row[key]??'').replaceAll('"','""')}"`).join(','))],blob=new Blob(['\ufeff'+lines.join('\n')],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`finops-${state.page}-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(url);}
async function bootstrap(){state.bootstrap=await api('/bootstrap',{range:false});const badge=document.querySelector('#mode-badge');badge.textContent=state.bootstrap.mode==='demo'?'演示数据':'实时数据';badge.className=`mode-badge ${state.bootstrap.mode}`;const sync=await api('/sync-state',{range:false});applySyncState(sync);await render();}
document.querySelector('#nav').addEventListener('click',(event)=>{const button=event.target.closest('.nav-item');if(!button)return;state.page=button.dataset.page;document.querySelector('#sidebar').classList.remove('open');document.querySelector('#drawer-backdrop').classList.remove('show');render();});
rangeSelect?.addEventListener('change',(event)=>setRange(event.target.value));
rangeTabs?.addEventListener('click',(event)=>{const button=event.target.closest('[data-range]');if(button)setRange(button.dataset.range);});
const refresh=async()=>{setRefreshState(true);try{await render();const sync=await api('/sync-state',{range:false});applySyncState(sync);}finally{setRefreshState(false);}};
refreshButton?.addEventListener('click',refresh);sidebarRefresh?.addEventListener('click',refresh);document.querySelector('#export-button').addEventListener('click',exportCsv);document.querySelector('#modal-close').addEventListener('click',closeModal);document.querySelector('#modal-backdrop').addEventListener('click',(event)=>{if(event.target.id==='modal-backdrop')closeModal();});document.querySelector('#menu-button').addEventListener('click',()=>{document.querySelector('#sidebar').classList.add('open');document.querySelector('#drawer-backdrop').classList.add('show');});document.querySelector('#drawer-backdrop').addEventListener('click',()=>{document.querySelector('#sidebar').classList.remove('open');document.querySelector('#drawer-backdrop').classList.remove('show');});document.addEventListener('keydown',(event)=>{if(event.key==='Escape'){closeModal();document.querySelector('#sidebar').classList.remove('open');document.querySelector('#drawer-backdrop').classList.remove('show');}});window.addEventListener('resize',()=>{const canvas=document.querySelector('#trend-chart');if(canvas&&state.page==='overview')api('/trend').then((items)=>drawTrend(canvas,items));});
bootstrap().catch((error)=>{content.innerHTML=`<div class="empty"><strong>无法启动工作台</strong><p>${escapeHtml(error.message)}</p></div>`;});
